export const REDUX = {
    AUTHEN: {
        FAIL_AUTHEN: "FAIL_AUTHEN",
        EXACT_AUTHEN: "EXACT_AUTHEN",
    },
    EMPLOYER_DETAIL: {
        GET_EMPLOYER_DETAIL: "GET_EMPLOYER_DETAIL",
    },
    EMPLOYER_MORE_JOB: {
        GET_EMPLOYER_MORE_JOB: "EMPLOYER_MORE_JOB",
    },
    HIGH_LIGHT: {
        GET_HIGH_LIGHT_JOB: 'GET_HIGH_LIGHT_JOB',
    },
    HOT_JOB: {
        GET_HOT_JOB: 'GET_HOT_JOB',
    },
    JOB_DETAIL: {
        GET_JOB_DETAIL: 'GET_JOB_DETAIL',
    },
    JOB_RESULT: {
        GET_JOB_RESULT: "GET_JOB_RESULT",
        SEARCH_JOB_DTO: "SEARCH_JOB_DTO"
    },
    JOB_SAVE: {
        GET_JOB_SAVE: "GET_JOB_SAVE"
    },
    MAP: {
        SET_MAP_STATE: 'SET_MAP_STATE'
    },
    MOBILE_STATE: {
        SET_MOBILE_STATE: "SET_MOBILE_STATE"
    },
    NOTI: {
        GET_NOTI: 'GET_NOTI'
    },
    PERSON_INFO: {
        GET_PERSON_INFO: 'PERSONAL_INFO'
    },
    POPUP: {
        OPEN_POPUP: 'OPEN_POPUP',
        CLOSE_POPUP: 'CLOSE_POPUP',
    },
    SIDE_BAR: {
        OPEN_SIDE_BAR: 'OPEN_SIDE_BAR',
        CLOSE_SIDE_BAR: 'CLOSE_SIDE_BAR',
    },

    CHAT_ROOM: {
        SET_CHAT_ROOM: 'SET_CHAT_ROOM'
    }
}

export const REDUX_SAGA = {
    EMPLOYER_DETAIL: {
        GET_EMPLOYER_DETAIL_DATA: 'GET_EMPLOYER_DETAIL_DATA',
    },

    EMPLOYER_MORE_JOB: {
        GET_EMPLOYER_MORE_JOB_DATA: 'GET_EMPLOYER_MORE_JOB_DATA',
    },

    HIGH_LIGHT: {
        GET_HIGH_LIGHT_DATA: 'GET_HIGH_LIGHT_DATA',
    },
    HOT_JOB: {
        GET_HOT_JOB: 'GET_HOT_JOB_DATA',
    },
    JOB_DETAIL: {
        GET_JOB_DETAIL: 'GET_JOB_DETAI_DATA',
    },
    JOB_RESULT: {
        GET_JOB_RESULT: "GET_JOB_RESULT_DATA",
    },
    JOB_SAVE: {
        GET_JOB_SAVE: "GET_JOB_SAVE_DATA"
    },
    NOTI: {
        GET_NOTI: 'GET_NOTI_DATA'
    },
    PERSON_INFO: {
        GET_PERSON_INFO: 'PERSONAL_INFO_DATA'
    },
}