export const REDUX = {
    AUTHEN: {
        FAIL_AUTHEN: "FAIL_AUTHEN",
        EXACT_AUTHEN: "EXACT_AUTHEN",
    },
    PENDING_JOBS: {
        GET_PENDING_JOBS: "GET_PENDING_JOBS",
    },

    JOB_NAME: {
        GET_JOB_NAME: "GET_JOB_NAME",
    },

    TYPE_MANAGEMENT: {
        GET_TYPE_MANAGEMENT: "GET_TYPE_MANAGEMENT",
    },

    ANNOUNCEMENTS: {
        GET_ANNOUNCEMENTS: "GET_ANNOUNCEMENTS"
    }
}

export const REDUX_SAGA = {

    PENDING_JOBS: {
        GET_PENDING_JOBS: "GET_PENDING_JOBS_DATA",
    },

    JOB_NAME: {
        GET_JOB_NAME: "GET_JOB_NAME_DATA",
    },

    TYPE_MANAGEMENT: {
        GET_TYPE_MANAGEMENT: "GET_TYPE_MANAGEMENT_DATA",
    },

    ANNOUNCEMENTS: {
        GET_ANNOUNCEMENTS: "GET_ANNOUNCEMENTS_DATA"
    }
}