export const breakCumb =  [
    {label: "pending-jobs", name: "Xét duyệt bài đăng", icon: "clock-circle", url: "/pending-jobs" },
    {label: "data", name: "Danh mục dữ liêu", icon: null, url: "/data"},
    {label: "job-management", name: "Quản lý bài đăng", icon: "file", url: "/"},
    {label: "create", name: "Tạo mới", icon: null, url: "/create"},
    {label: "fix", name: "Chỉnh sửa", icon: null, url: "/fix"},
    {label: "languages", name: "Ngôn ngữ", icon: null, url: "/languages"},
    {label: "majors", name: "Loại ngành nghề", icon: null, url: "/languages"},
    {label: "type-schools", name: "Loại trường", icon: null, url: "/type-schools"},
    {label: "regions", name: "Tỉnh thành", icon: null, url: "/regions"},
    {label: "job-names", name: "Loại công việc", icon: null, url: "/job-names"},
    {label: "list", name: "Danh sách", icon: null, url: "/list"},
    {label: "skills", name: "Kỹ năng", icon: null, url: "/skills"},
    {label: "job-groups", name: "Nhóm công việc", icon: null, url: "/job-groups"},
    {label: "branches", name: "Nhóm ngành", icon: null, url: "/branches"},
    {label: "role-admins", name: "Quản trị viên", icon: null, url: "/role-admins"},
    {label: "roles", name: "Quyền", icon: null, url: "/roles"},
];