export const TYPE = {
    ALL: "ALL",

    SUCCESS: 'success',
    ERROR: "error",
    WARNING: "warning",

    REJECTED: "REJECTED",
    ACCEPTED: "ACCEPTED",
    PENDING: "PENDING",

    PARTTIME: "PARTTIME",
    FULLTIME: "FULLTIME",
    INTERNSHIP: "INTERNSHIP",

    CANDIDATE: "CANDIDATE",
    EMPLOYER: "EMPLOYER",
    SCHOOL: "SCHOOL",
    PUBLIC: "PUBLIC",
    STUDENT: "STUDENT",

    CREATE: "CREATE",
    EDIT: "EDIT",
    DELETE: "DELETE",
    DELETE_SELECTED: "DELETE_SELECTED",

    INPUT: "INPUT",
    SELECT: "SELECT",

    NORMAL_LOGIN: "NORMAL_LOGIN",
    REFESH_LOGIN: "REFESH_LOGIN"
};
